### ISSUE TITLE
Unable to commit to the qa repo

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/qa#846]
Pre-commit hooks are not passing in the qa repo at the moment. Something assumes that there is a package.json in this repo. Full error pasted below. @samreid confirmed the problem and asked to be assigned to this issue at high priority. Thank you!

```
qa:
C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\grunt-legacy-util\index.js:55
  if (!nodeUtil.isError(err)) { err = new Error(err); }
                                      ^

Error: Unable to read "../qa/package.json" file (Error code: ENOENT).
    at Object.util.error (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\grunt-legacy-util\index.js:55:39)
    at Object.file.read (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\grunt\lib\grunt\file.js:224:22)
    at Object.file.readJSON (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\grunt\lib\grunt\file.js:230:18)
    at getPhetLibs (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\getPhetLibs.js:36:38)
    at C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\getPhetLibs.js:32:43
    at arrayReduce (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\lodash\lodash.js:697:21)
    at Function.reduce (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\lodash\lodash.js:9749:14)
    at getPhetLibs (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\getPhetLibs.js:31:14)
    at getPhetLibs (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\getPhetLibs.js:28:12)
    at module.exports (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\reportMedia.js:36:24) {
  origError: Error: ENOENT: no such file or directory, open '../qa/package.json'
      at Object.openSync (node:fs:585:3)
      at Object.readFileSync (node:fs:453:35)
      at Object.file.read (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\grunt\lib\grunt\file.js:214:19)
      at Object.file.readJSON (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\grunt\lib\grunt\file.js:230:18)
      at getPhetLibs (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\getPhetLibs.js:36:38)
      at C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\getPhetLibs.js:32:43
      at arrayReduce (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\lodash\lodash.js:697:21)
      at Function.reduce (C:\Users\Jesse\Documents\Development\phetsims\chipper\node_modules\lodash\lodash.js:9749:14)
      at getPhetLibs (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\getPhetLibs.js:31:14)
      at getPhetLibs (C:\Users\Jesse\Documents\Development\phetsims\chipper\js\grunt\getPhetLibs.js:28:12) {
    errno: -4058,
    syscall: 'open',
    code: 'ENOENT',
    path: '../qa/package.json'
  }
}

```

**Comment by samreid** [comment]
It seems it was an easy fix, closing.
